export const FILE_REPOSITORY = Symbol('FILE_REPOSITORY');
export const CAR_MODEL_PROJECTION = Symbol('CAR_MODEL_PROJECTION');
export const WEBSOCKET_SERVICE_OUTPUT_PORT = Symbol(
  'WEBSOCKET_SERVICE_OUTPUT_PORT',
);
